### ISSUE TITLE
Missing GTop when installed from flatpak under EndlessOS

### ISSUE THREAD

**Issue by btreut** [nlpsuge/gnome-shell-extension-another-window-session-manager#79]
I installed the "Another Window Session Manager" as an extension in the Gnome Extension Manager under EndlessOS. Gnome Extension Manager was installed from flatpak on flathub. "Another Window Session Manager" is complaining that it is missing GTop/Typelibs:
`   Requiring GTop, version none: Typelib file for namespace 'GTop' (any version) not found`

See also my [post on the EndlessOS community platform](https://community.endlessos.com/t/missing-apps-for-another-window-session-manager/20103).

Any ideas, how to install the missing pieces?

**Comment by nlpsuge** [comment]
Hi, 

To fix this problem, you will have to install `gtop`, please visit:
https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager#dependencies

**Comment by btreut** [comment]
> Since Endless OS is a Debian derivative distribution, you can install the `gtop` via:
> `apt install gir1.2-gtop-2.0 libgtop2-dev`

sorry, no way to install anything via ```apt``` under EndlessOS, see this [post ](https://community.endlessos.com/t/apt-get-and-flatpak-how-to-download-and-install-from-e-g-github/6170 )and the referenced stuff in it.

**Comment by nlpsuge** [comment]
> > Since Endless OS is a Debian derivative distribution, you can install the `gtop` via:
> > `apt install gir1.2-gtop-2.0 libgtop2-dev`
> 
> sorry, no way to install anything via `apt` under EndlessOS, see this [post ](https://community.endlessos.com/t/apt-get-and-flatpak-how-to-download-and-install-from-e-g-github/6170)and the infos referenced in it.

I see. Maybe I should `try...catch...` the imports of `gtop` and ignore the errors if it's not installed, so it won't cause the extension unable to load. I'll do it later and let you know when it's done.

**Comment by nlpsuge** [comment]
> Great, I'll be patient.

I've pushed a fix to the [main](https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager) branch for this issue. You can copy the files to `~/.local/share/gnome-shell/extensions/another-window-session-manager@gmail.com` and restart gnome shell to take effect.

**Comment by nlpsuge** [comment]
> > You can copy the files to ~/.local/share/gnome-shell/extensions/[another-window-session-manager@gmail.com](mailto:another-window-session-manager@gmail.com) and restart gnome shell to take effect.
> 
> thanks, but I don't know how I can copy files nor which files from the [main](https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager) branch ...

Just run the below command:
```
cd /tmp
# Or download the source code
git clone https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager.git
cp -rp gnome-shell-extension-another-window-session-manager/* ~/.local/share/gnome-shell/extensions/another-window-session-manager@gmail.com/
```

Then restart gnome shell using `alt+f2 type r` on X11 or logout and login on Wayland.

**Comment by btreut** [comment]
thanks, I"ll try it.

**Comment by nlpsuge** [comment]
![image](https://user-images.githubusercontent.com/2271720/232061705-15e5ce7c-fb85-4e83-9f18-4679379b406f.png)

Please disable this switch, so that patches that you mentioned should never appear again when you `Logout/Restart/Shutdown`.

**Comment by nlpsuge** [comment]
@btreut What's your gnome shell version?

**Comment by btreut** [comment]
> @btreut What's your gnome shell version?

 $ gnome-shell --version
 GNOME Shell 41.9

> @btreut Please disable this switch ...

I already used this toggle, otherwise I would not be able to logout/restart/shutdown.

EndlessOS uses some own extensions to the gnome shell, maybe there is some interference:
![grafik](https://user-images.githubusercontent.com/8996291/232099363-e9427a0a-aaf4-4c19-a340-5727f568e01d.png)

**Comment by nlpsuge** [comment]
> and I fear, I do not have any chance to upgrade to a newer version on my own ...
> 
> >

No need to upgrade to a newer version, GNOME Shell 41.9 is supported by AWSM.


> EndlessOS uses some own extensions to the gnome shell, maybe there is some interference:

I think you can disable all system extensions which is provided by Endless OS, and then activate `Auto close session` again, and to see if that patch can be rendered to a dialog normally.

**Comment by nlpsuge** [comment]
> Apr 14 09:54:25 acer-spin-bernhard gnome-shell[2432]: clutter_actor_add_child: assertion 'child->priv->parent == NULL' failed
> Apr 14 09:54:25 acer-spin-bernhard gnome-shell[2432]: JS ERROR: [ERROR ][Another window session manager] undefined: TypeError: actor.connectObject is not a function
> _setInitialKeyFocus@/sysroot/home/bernhard/.local/share/gnome-shell/extensions/[another-window-session-manager@gmail.com](mailto:another-window-session-manager@gmail.com)/ui/autoclose.js:490:19
> addButton@/sysroot/home/bernhard/.local/share/gnome-shell/extensions/[another-window-session-manager@gmail.com](mailto:another-window-session-manager@gmail.com)/ui/autoclose.js:478:22
> _init@/sysroot/home/bernhard/.local/share/gnome-shell/extensions/[another-window-session-manager@gmail.com](mailto:another-window-session-manager@gmail.com)/ui/autoclose.js:345:39
> _overrideEndSessionDialog/EndSessionDialog.EndSessionDialog.prototype._confirm@/sysroot/home/bernhard/.local/share/gnome-shell/extensions/[another-window-session-manager@gmail.com](mailto:another-window-session-manager@gmail.com)/ui/autoclose.js:148:62
> action/signalId<@resource:///org/gnome/shell/ui/endSessionDialog.js:450:30
> _closeComplete@resource:///org/gnome/shell/ui/modalDialog.js:167:14
> onComplete@resource:///org/gnome/shell/ui/modalDialog.js:186:40
> _makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:153:13
> _easeActor/<@resource:///org/gnome/shell/ui/environment.js:240:64


I reproduce this error on Fedora 35.

The `connectObject` function is only added in recent versions after 41.

**Comment by btreut** [comment]
> I reproduce this error on Fedora 35.

so I guess there is no need to disable the EndlessOS extensions.

**Comment by nlpsuge** [comment]
> > I reproduce this error on Fedora 35.
> 
> so I guess there is no need to disable the EndlessOS extensions.

Yes.

**Comment by nlpsuge** [comment]
BTW, the upstream changes related to this issue is here https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/26235bbe5433c48b81bd3917aaf9ef14ff1929b2


I don't think I have more free time to fix it recently unfortunately....

**Comment by btreut** [comment]
> I don't think I have more free time to fix it recently unfortunately

sorry to hear that. So I have to be patient and wait for upstream fixes

**Comment by nlpsuge** [comment]
> So I have to be patient and wait for upstream fixes

Not really. It's a compatibility issue with gnome shell 41, which means some code in `/sysroot/home/bernhard/.local/share/gnome-shell/extensions/another-window-session-manager@gmail.com/ui/autoclose.js` has to be modified to be compatible with gnome shell 41.

**Comment by btreut** [comment]
I'll try my best, although Javascript is not my favorite language ...

**Comment by btreut** [comment]
> ... I'll ask there before digging into js

and I got the answer

> Sorry, no timeline for that at present.

so I finally tried to dig into the code and commented out in `autoclose.js` two infringing lines (490-491). Now the little black patches do not pop up, but it also doesn't work correctly. The following other error message appears shortly
![grafik](https://user-images.githubusercontent.com/8996291/234252319-ea3b3918-0f13-431d-9e93-73f6e79d4dd2.png)
so I give up for now ...

**Comment by nlpsuge** [comment]
Hi @btreut ,

The above issues have been fixed in PR #88, could you please test it, you can visit this link
https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/tree/dev-gnome41-compatibility to download the code. 

After downloading, copy the files to the AWSM extension folder:
`cp -rp gnome-shell-extension-another-window-session-manager/* ~/.local/share/gnome-shell/extensions/another-window-session-manager@gmail.com/`

Then restart gnome shell (using alt+f2 type r for X11 or logout and login for Wayland).

**Comment by btreut** [comment]
branch dev-gnome41-compatibilit behaves slightly better than master. But now I encounter the same problem as described in [ydotoool.service not found #83](https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/issues/83#issue-1723538298) but it is not obvious to me, what I have to do under EndlessOS to enable that service (no way to install with apt):
![Screenshot_Cutout-60_2023-07-24 11-42-29](https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/assets/8996291/45128ae4-d2eb-4852-a019-720fd3381502)

**Comment by btreut** [comment]
strange enough: I logged out (session was X11) by clicking "Log out now" in the window above and ignoring the ydotool.service message and switched to Wayland and got lots of applications restored. It may be possible that I saved these quite some months ago by accident, when I tried to use the session manager the first times. I'll retry now again to save only one application (Firefox) and switch back to X11. I'll edit/update this comment after coming back.

**Comment by nlpsuge** [comment]
> no way to install with apt

Oh, I forget this point, so you can't install `ydotool` either.

> Apparently session saving seem to also work without the ydotool.service.
Yes, they are independent each other.

> As far as I understand ydotool.service is used to feed automagically keystrokes to the X11/Wayland input queue

Yes, it is. AWSM uses `ydotool` to send shortcuts to the running apps to close them.
![image](https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/assets/2271720/ddf2396e-6340-4179-bfbb-8a33526a23f0)

If `ydotool` is not installed, the above two sections of settings won't work properly. You can disable this function by switching off `Close by rules`:
![image](https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/assets/2271720/09ac7741-a5a3-4634-a2ce-72daf1e4561b)

And the below prompt dialog should be never shown again.
![image](https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/assets/2271720/20a34639-852a-490d-9186-fc09c67ed232)


> It may be possible that I saved these quite some months ago by accident, when I tried to use the session manager the first times.

Yes, you are right.

**Comment by btreut** [comment]
"Close by rules" is switched off in my setup, but that dialog still appears:
![Screenshot_AWSM_Cutout60_2023-07-24_16-19-15](https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/assets/8996291/d2dc85b1-50d4-4330-8b55-a89ab062dae3)

**Comment by nlpsuge** [comment]
@btreut 

> > And the below prompt dialog should be never shown again.
> > [...]
> 
> "Close by rules" is switched off in my setup, but that dialog still appears: ![Screenshot_AWSM_Cutout60_2023-07-24_16-19-15](https://user-images.githubusercontent.com/8996291/255619222-d2dc85b1-50d4-4330-8b55-a89ab062dae3.png)

This is a bug and it's fixed. Please redownload the code and try again.

**Comment by btreut** [comment]
> This is a bug and it's fixed. Please redownload the code and try again.

done, looks good on the first attempts using it.

**Comment by nlpsuge** [comment]
> > This is a bug and it's fixed. Please redownload the code and try again.
> 
> done, looks good on the first attempts using it.

OK, I will push a new version to the E.G.O website in this week, thanks.

**Comment by nlpsuge** [comment]
> > This is a bug and it's fixed. Please redownload the code and try again.
> 
> done, looks good on the first attempts using it.

OK, I will push a new version to the E.G.O website in this week, thanks.
